added landing page, not done
almir0201/Pokedex pull request #121
Opened 2024-03-13 22:13 UTC by almir0201

2024-03-21 23:35 UTC, Shekey commented
Comments:
1. You have overflow so you want to prevent scroll, 1 solution can be to add overflow-hidden to whole section (DESKTOP)
2. "Find all your favourite pokemon" space between lines are not matched, and font feels awkward, the real question if font even works
3. Min height of page should be 100vh, I see some blank space at the bottom (DESKTOP)
4. Make with ❤️ for the PokéSpartans team Platzi Master and whole footer needs to follow header width size, it needs to match exaclty
5. Instead of using "class="absolute w-[18%] lg:w-full max-w-[133px] lg:max-w-[167px] ml-[7%] top-[4%] lg:mt-3 lg:ml-9"

you could replace margins with left-0 and top-9, it makes more sense



Overall: pretty close, fix those things above and you can merge it
@almir0201

2024-03-25 10:41 UTC, almir0201 commented
Close #121

2024-03-27 15:21 UTC, almir0201 commented
@Shekey  for easier review here are issues 
![image](https://github.com/almir0201/Pokedex/assets/59663344/dee37d8f-eb04-4315-9de5-7ec14c34e8bc)

2024-03-27 23:21 UTC, Shekey requested changes

2024-03-27 23:21 UTC, Shekey commented on src/components/ui/Hero/Hero.js
> +          type={`${width > 1023 ? 'h1' : 'h5'}`}
why not just width>1023 ? xx : xx

2024-03-27 23:21 UTC, Shekey commented on src/components/ui/Hero/Hero.js
> +          variant={`${width > 1279 ? '2xl' : 'xl'}`}
same as above

2024-03-27 23:21 UTC, Shekey commented on src/components/ui/Footer/Footer.js
> +      <div className={cn(className)}>
just className if you don't have nothing to combine with

2024-03-29 19:55 UTC, Shekey approved these changes

2024-03-29 22:37 UTC, merged