made 404 page
almir0201/Pokedex pull request #127
Opened 2024-03-29 15:13 UTC by almir0201

2024-03-29 15:13 UTC, almir0201 commented
Close #127

2024-03-29 19:58 UTC, Shekey requested changes

2024-03-29 19:58 UTC, Shekey commented on src/pages/ErrorPage.js
> +          {width > 1023 ? (
div with className hidden md:block will replace this

2024-03-29 19:58 UTC, Shekey commented on src/pages/ErrorPage.js
> +          {width > 1023 ? (
same like above

2024-03-29 19:58 UTC, Shekey commented on src/pages/ErrorPage.js
> +            variant={width > 1023 ? 'lg' : 'md'}
add two buttons with classes hidden md:block and block md:hidden

2024-03-29 19:58 UTC, Shekey commented on src/pages/ErrorPage.js
> +          o={'..'}
what's this O prop?

2024-03-30 23:36 UTC, Shekey requested changes

2024-03-30 23:36 UTC, Shekey commented on src/components/ui/Links/Links.js
> +export const Links = ({ children, to, className }) => {
also rename this component to singular, it was confusing to me reading this

rename to link

2024-04-01 22:17 UTC, Shekey commented on src/components/header/Header.js
> +                .filter((route) => route.title !== '404')
I think now you don't need this, right?

2024-04-03 21:37 UTC, Shekey approved these changes

2024-04-04 15:08 UTC, merged